/* (re)create objects. Run me with */
/* STRREXPRC SRCMBR(COMPILE) SRCFILE(CISCO/SOURCES) */

"CHGCURLIB CURLIB(CISCO)"

/* REPLACE(*YES) is unknown to CRTLF, so delete for later recreation. */
"DLTF FILE(ACMATCHRPL)"
"DLTF FILE(ACUPDLF)"
"DLTF FILE(DCAOSMATCH)"
"DLTF FILE(HSTPOSLF1)"
"DLTF FILE(HSTPOSLF2)"
"DLTF FILE(HSTPOSLF3)"
"DLTF FILE(OSMATCH1LF)"
"DLTF FILE(OSMATCH2LF)"
"DLTF FILE(OSMATCH3LF)"
"DLTF FILE(OSMATCH4LF)"
"DLTF FILE(OSMATCH5LF)"
"DLTF FILE(OSMATCHMAX)"
"DLTF FILE(OSMATCHRPL)"
"DLTF FILE(OSMATCHWLF)"
"DLTF FILE(OSMRPTMLF)"
"DLTF FILE(OSMRPTOLF)"
"DLTF FILE(OSUPDTELF)"
"DLTF FILE(RPNOMAILLF)"
"DLTF FILE(RPNOSVCLF)"
"DLTF FILE(RPUPTIMLF)"
"DLTF FILE(SERNOLF)"
"DLTF FILE(SERVSTSLF)"

acupdlf.dds
hstposlf.dds
osmatch1lf.dds
osmatch2lf.dds
osmatch3lf.dds
osmatch4lf.dds
osmatch5lf.dds
osmatchwlf.dds
osmrptmlf.dds
osmrptolf.dds
osupdtelf.dds
rptuptimlf.dds
sernolf.dds


/* Above deletion included join LFs, so we can safely change PFs now. */
"CHGPF FILE(ACDCAPF) SRCFILE(SOURCES)"
"CHGPF FILE(ACMATCHPF) SRCFILE(SOURCES)"
"CHGPF FILE(CFGVERPF) SRCFILE(SOURCES)"
"CHGPF FILE(DCAPF) SRCFILE(SOURCES)"
"CHGPF FILE(HSTPF) SRCFILE(SOURCES)"
"CHGPF FILE(INVPF) SRCFILE(SOURCES)"
"CHGPF FILE(OSMATCHPF) SRCFILE(SOURCES)"
"CHGPF FILE(VLANPF) SRCFILE(SOURCES)"

/* Recreate LFs. */
"CRTLF FILE(ACMATCHRPL) SRCFILE(SOURCES)"
"CRTLF FILE(ACUPDLF) SRCFILE(SOURCES)"
"CRTLF FILE(DCAOSMATCH) SRCFILE(SOURCES)"
"CRTLF FILE(HSTPOSLF1) SRCFILE(SOURCES)"
"CRTLF FILE(HSTPOSLF2) SRCFILE(SOURCES)"
"CRTLF FILE(HSTPOSLF3) SRCFILE(SOURCES)"
"CRTLF FILE(OSMATCH1LF) SRCFILE(SOURCES)"
"CRTLF FILE(OSMATCH2LF) SRCFILE(SOURCES)"
"CRTLF FILE(OSMATCH3LF) SRCFILE(SOURCES)"
"CRTLF FILE(OSMATCH4LF) SRCFILE(SOURCES)"
"CRTLF FILE(OSMATCH5LF) SRCFILE(SOURCES)"
"CRTLF FILE(OSMATCHMAX) SRCFILE(SOURCES)"
"CRTLF FILE(OSMATCHRPL) SRCFILE(SOURCES)"
"CRTLF FILE(OSMATCHWLF) SRCFILE(SOURCES)"
"CRTLF FILE(OSMRPTMLF) SRCFILE(SOURCES)"
"CRTLF FILE(OSMRPTOLF) SRCFILE(SOURCES)"
"CRTLF FILE(OSUPDTELF) SRCFILE(SOURCES)"
"CRTLF FILE(RPNOMAILLF) SRCFILE(SOURCES)"
"CRTLF FILE(RPNOSVCLF) SRCFILE(SOURCES)"
"CRTLF FILE(RPUPTIMLF) SRCFILE(SOURCES)"
"CRTLF FILE(SERNOLF) SRCFILE(SOURCES)"
"CRTLF FILE(SERVSTSLF) SRCFILE(SOURCES)"

"CRTDSPF FILE(ACMATCHDF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(ADSRVRUNDF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(CFGVERDF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(DCADF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(HSTDF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(INVDF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(OSMATCHDF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(OSMRPTDF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(SERNODF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(SERVSTS1DF) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTDSPF FILE(SERVSTS2DF) SRCFILE(SOURCES) REPLACE(*YES)"

"CRTPRTF FILE(RPALLDEVPT) SRCFILE(SOURCES) PAGESIZE(74 166 *ROWCOL) OVRFLW(72)"
"CRTPRTF FILE(RPNOMAILPT) SRCFILE(SOURCES) PAGESIZE(74 166 *ROWCOL) OVRFLW(72)"
"CRTPRTF FILE(RPNOSVCPT) SRCFILE(SOURCES) PAGESIZE(74 166 *ROWCOL) OVRFLW(72)"
"CRTPRTF FILE(RPUPDTEPT) SRCFILE(SOURCES) PAGESIZE(74 166 *ROWCOL) OVRFLW(72)"
"CRTPRTF FILE(RPUPTIMPT) SRCFILE(SOURCES) PAGESIZE(74 166 *ROWCOL) OVRFLW(72)"

"CRTBNDRPG PGM(ACMATCHPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(CFGVERPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(DCAPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(HSTPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(INVPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(OSMATCHPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(OSMRPTPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(RPALLDEVPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(RPNOMAILPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(RPNOSVCPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(RPUPDTEPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(RPUPTIMPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(SERNOPG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(SERVSTS1PG) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTBNDRPG PGM(SERVSTS2PG) SRCFILE(SOURCES) REPLACE(*YES)"

"CRTSQLRPGI OBJ(ADSRVRUNPG) SRCFILE(SOURCES) OBJTYPE(*PGM) REPLACE(*YES)"
"CRTCLPGM PGM(RPPRTPG) SRCFILE(SOURCES) REPLACE(*YES)"

"CRTPNLGRP PNLGRP(ACMATCHHP) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTPNLGRP PNLGRP(CFGVERHP) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTPNLGRP PNLGRP(DCAHP) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTPNLGRP PNLGRP(HSTHP) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTPNLGRP PNLGRP(INVHP) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTPNLGRP PNLGRP(OSMATCHHP) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTPNLGRP PNLGRP(OSMRPTHP) SRCFILE(SOURCES) REPLACE(*YES)"
"CRTPNLGRP PNLGRP(SERNOHP) SRCFILE(SOURCES) REPLACE(*YES)"

"CRTMNU MENU(CMDCISCO) TYPE(*UIM) SRCFILE(SOURCES) INCFILE(QGPL/MENUUIM)"
/* vim: ft=rexx
 */
